### ISSUE TITLE
Signlink disables the option for other plugins to update signs

### ISSUE THREAD

**Issue by lipe123** [bergerkiller/SignLink#3]
Plugins that use signs like Stargate/lift/bananaregion cant update the text on the signs when signlink is active.

If I use plugman to do /plugman disable signlink all the other plugins can start using signs again.

Please look into this.

Using signlink 1.22
This happened on CB 2126 and 2149
Also using spoutplugin 1083

**Comment by bergerkiller** [comment]
@lipe123 Can you further describe what you mean with 'cant update the text on the signs'? What happens exactly? Or, what is supposed to happen (for example, in Stargate) and what happens? Is this a virtual issue (the text has changed, but is not seen by players) or does it physically fail to change?

**Comment by lipe123** [comment]
It's virtual, the text is on the sign but uers don't see it, even after a relog.

for stargate for example you put this on the sign:
myhome
thedestination
thenetwork
F
Once you do that the sign will immediately change to:
--myhome--
to:
--thedestination--
(mynetwork)

At the moment that change does not happen, the original text stays on the sign.

The lift plugin requires you put blank signs on each floor the elevator will stop, then you rightclick them once you made them all and it will write: 
Floor : 1 
Destination: 2

on the sign for example, you can then rightclick the sign to change the dest. Right now the signs stay blank, if you rightclick them the dest changes but you cant tell what it is.

When the server restarts the "bad" signs work and display their dynamic text no problem, with signlink running also. It's only the newly created signs that get "blocked" from updating by signlink.
If I do /plugman disable signlink and then create a new lift/stargate sign it updates instantly like it should without a restart.

**Comment by bergerkiller** [comment]
Mhhh then this is a sync-text issue in the update routine, I'll first try and reproduce it and then look for ways to fix it....

**Comment by bergerkiller** [comment]
Verified; I made TrainCarts record the time for the trigger and it didn't change the sign. Now looking at counter-measurements...

**Comment by bergerkiller** [comment]
Ok fixed it, expect it fixed in version 1.23 I will upload later today :)

**Comment by lipe123** [comment]
Thanks I'll test tonight and let you know

**Comment by bergerkiller** [comment]
Uploaded (with a lot of other bugfixes...)
